<a href="https://colab.research.google.com/github/nxnatnat/H8_3/blob/main/Pertemuan_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy

In [ ]:
numpy.__version__

'1.21.5'

In [ ]:
numpy.NaN

nan

In [ ]:
numpy.arange(0,1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
import numpy as np

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[2]

array([ 9, 10, 11, 12])

In [ ]:
 np.array([[0,0,0],
 [1,1,1]])

array([[0, 0, 0],
       [1, 1, 1]])

In [ ]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [ ]:
np.arange(-2,-100,-5)

array([ -2,  -7, -12, -17, -22, -27, -32, -37, -42, -47, -52, -57, -62,
       -67, -72, -77, -82, -87, -92, -97])

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [ ]:
x = [1,2]
x.append([10,11])

In [ ]:
x

[1, 2, [10, 11]]

In [ ]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr = np.array([[2,1,3,4,5,6,7,8], [3,4,5,1,2,6,7,8]])
arr

array([[2, 1, 3, 4, 5, 6, 7, 8],
       [3, 4, 5, 1, 2, 6, 7, 8]])

In [ ]:
np.sort(arr)

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
arr.ndim

2

In [ ]:
arr.size

16

In [ ]:
arr.shape

(2, 8)

In [ ]:
np.array([[[0,1,2,3],
          [4,5,6,7]],
          
          [[0,1,2,3],
           [4,5,6,7]],
           
          [[0,1,2,3],
           [4,5,6,7]]])

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [ ]:
arr.ndim

2

In [ ]:
arr.size

16

In [ ]:
arr.shape

(2, 8)

In [ ]:
 a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

# Convert 1D to 2D

In [ ]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [ ]:
a2 = a[np.newaxis]
a2.shape

(1, 6)

In [ ]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [ ]:
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [ ]:
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [ ]:
b = np.expand_dims(a, axis=1)

In [ ]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [ ]:
c

array([[1, 2, 3, 4, 5, 6]])

# Indexing and Slicing

In [ ]:
data = np.array([1,2,3,])
data

array([1, 2, 3])

In [ ]:
data[0]

1

In [ ]:
data[1]

2

In [ ]:
data[0:2]

array([1, 2])

In [ ]:
data[1:]

array([2, 3])

In [ ]:
data[-2:]

array([2, 3])

In [ ]:
a = np.array([[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12]])

# Creating array from existing data

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [ ]:
a_1 = np.array([[1,2], [2,2]])
a_2 = np.array([[3,3], [4,6]])

In [ ]:
a_1

array([[1, 2],
       [2, 2]])

In [ ]:
a_2

array([[3, 3],
       [4, 6]])

In [ ]:
np.hstack((a_1, a_2))

array([[1, 2, 3, 3],
       [2, 2, 4, 6]])

In [ ]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
                   [13,14,15,16,17,18,19,20,21,22,23,24]])
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic array operations

In [ ]:
array_1 - array_2
array_1 + array_2
array_1 + array_2
array_1 / array_2

In [ ]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
a.sum()

10

In [ ]:
b = np.array([[1,1], [2,2]])
b

array([[1, 1],
       [2, 2]])

In [ ]:
b.sum(axis=1)

array([2, 4])

In [ ]:
data = np.array([1,2])
data

array([1, 2])

In [ ]:
ones = np.ones(2)
ones

array([1., 1.])

In [ ]:
data + ones

array([2., 3.])

In [ ]:
data - ones

array([0., 1.])

In [ ]:
data / ones

array([1., 2.])

In [ ]:
data = ones

# Broadcasting

# More array operations

# Matrices

In [ ]:
np.array

# Creating Matrices

# Dot Product

In [ ]:
a_1 = np.array([[1,2,3], [4,5,6]])
a_1.shape

(2, 3)

In [ ]:
a_2 = np.array([[7,8], [9,10], [11,12]])
a_2.shape

(3, 2)

In [ ]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

# Matrix indexing

In [ ]:
data = np.array([[1,2], [3,4], [5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
data[0,1]

2

In [ ]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [ ]:
data[0:2, 1]

array([2, 4])

# matrix aggregation

In [ ]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
data.max()

6

In [ ]:
data.min()

1

In [ ]:
data.sum()

21

In [ ]:
data.std()

1.707825127659933

In [ ]:
data.max(axis=1)

array([2, 4, 6])

# Transposing and reshaping

In [ ]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
data_col = np.array([[1,2,3,4,5,6]])
data_col

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
data_col = data_col.T
data_col

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr = np.arange(6).reshape((2, 3)
                           arr

SyntaxError: unexpected EOF while parsing (883222038.py, line 1)

# N-dimension array

In [ ]:
ndarr = np.array([[[1, 2], [3,4]]
                  [[5, 6], [7,8]]])

# Flatten N-Dimension Array

In [ ]:
arrflat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arrflat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arrflat.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
error = (1/n) + np.sum(np.square(observed - prediction))

NameError: name 'n' is not defined